<?xml version="1.0" encoding="utf-8"?><Database Name="bdNomina" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=bdNomina;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bdNominaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.paValidUser" Method="paValidUser">
    <Parameter Name="user" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pwd" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="paValidUserResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fReg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.paNewMessagesByIdUser" Method="paNewMessagesByIdUser">
    <Parameter Name="idUserTo" Type="System.Int32" DbType="Int" />
    <ElementType Name="paNewMessagesByIdUserResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUserFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[user]" Member="user" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fReg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fIns" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.paGetUserData" Method="paGetUserData">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="paGetUserDataResult">
      <Column Name="[user]" Member="user" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fReg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>